"use strict";
let accessToken = "", current = null, prepared = null;
const element = id => document.getElementById(id);
const labels = {SUCCEEDED:"완료",FAILED:"실패",GAP:"누락 확인 필요",RUNNING:"진행 중",REJECTED:"거절",AWAITING_REVIEW:"검토 대기",HALTED:"중단",RESEARCH_ENABLED:"연구 허용",REVIEW_ACCEPTED_NOT_PROMOTED:"검토 수락·미승격"};
function rows(id, values) {
  const body=element(id); body.replaceChildren();
  for(const valuesRow of values){const row=document.createElement("tr");for(const value of valuesRow){const cell=document.createElement("td");cell.textContent=String(value??"-");row.append(cell);}body.append(row);}
  if(!values.length){const row=document.createElement("tr"),cell=document.createElement("td");cell.textContent="기록 없음";cell.colSpan=5;row.append(cell);body.append(row);}
}
function renderValidation(){rows("validations",(current?.workflow?.validations||[]).map(item=>[item.campaign,`${labels[item.state]||item.state} · 연구 동결`,item.reserved_engine_calls,item.attempts,item.corrected_lower_bound]));}
function draw(){const canvas=element("scores"),width=Math.max(280,canvas.clientWidth),scale=window.devicePixelRatio||1;canvas.width=width*scale;canvas.height=220*scale;const context=canvas.getContext("2d");context.scale(scale,scale);context.clearRect(0,0,width,220);context.strokeStyle="#d1dcd5";for(let index=0;index<4;index++){context.beginPath();context.moveTo(40,30+index*50);context.lineTo(width-20,30+index*50);context.stroke();}const scores=(current?.workflow?.trials||[]).map(item=>item.score).filter(value=>typeof value==="number");if(!scores.length)return;const lower=Math.min(0,...scores),upper=Math.max(0,...scores),range=upper-lower||1;context.strokeStyle="#146046";context.lineWidth=2;context.beginPath();scores.forEach((value,index)=>{const x=40+index*(width-70)/Math.max(1,scores.length-1),y=180-(value-lower)/range*150;if(index)context.lineTo(x,y);else context.moveTo(x,y);});context.stroke();}
async function refresh(){const response=await fetch("/api/status",{headers:{Authorization:`Bearer ${accessToken}`},cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.detail||"상태 조회 실패");current=result;const jobs=result.workflow?.jobs||[],trials=result.workflow?.trials||[];element("connection").textContent=`연결됨 · ${result.role}`;element("jobs-count").textContent=jobs.length;element("trials-count").textContent=trials.length;element("audit-count").textContent=result.audit_count;rows("jobs",jobs.map(item=>[item.run_id,labels[item.status]||item.status,item.attempts,item.updated_at]));rows("trials",trials.map(item=>[item.sequence,JSON.stringify(item.parameters),item.proposer_receipt?.model,item.score,labels[item.status]||item.status]));rows("reviews",result.reviews.map(item=>[item.id,labels[item.status]||item.status,item.revision]));rows("alerts",result.alerts.map(item=>[item.severity,item.target,item.message,item.observed_at]));element("audit-head").textContent=result.audit_head;element("target").replaceChildren();for(const item of result.reviews){const option=document.createElement("option");option.value=item.id;option.textContent=item.id;element("target").append(option);}element("refresh").disabled=false;element("logout").disabled=false;element("execute").disabled=result.role!=="OPERATOR"||!result.reviews.length;draw();}
async function report(operation){element("notice").textContent="";try{await operation();renderValidation();element("prepare").disabled=current?.role!=="OPERATOR";element("execute").disabled=!prepared||current?.role!=="OPERATOR";}catch(error){element("notice").textContent=error.message;if(error.message.includes("인증")){accessToken="";current=null;prepared=null;for(const id of ["jobs","trials","reviews","alerts","validations"])rows(id,[]);for(const id of ["jobs-count","trials-count","audit-count"])element(id).textContent="0";element("connection").textContent="인증 만료";element("audit-head").textContent="";element("prepared").textContent="";element("execute").disabled=true;element("prepare").disabled=true;draw();}}}
element("login").addEventListener("submit",event=>{event.preventDefault();accessToken=element("token").value;element("token").value="";element("command-token").value="";element("target").replaceChildren();prepared=null;element("prepared").textContent="";report(refresh);});element("refresh").addEventListener("click",()=>report(refresh));element("logout").addEventListener("click",()=>{accessToken="";current=null;location.reload();});
document.querySelectorAll("[data-tab]").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("[data-tab]").forEach(item=>item.setAttribute("aria-selected",String(item===button)));document.querySelectorAll("main section").forEach(section=>section.classList.toggle("active",section.id===button.dataset.tab));draw();}));
for(const id of ["target","action","reason"])element(id).addEventListener("input",()=>{prepared=null;element("prepared").textContent="";element("execute").disabled=true;});
element("prepare").addEventListener("click",()=>report(async()=>{const target=current?.reviews.find(item=>item.id===element("target").value);if(!target)throw new Error("검토 대상이 없습니다.");const command={request_id:crypto.randomUUID(),action:element("action").value,target:target.id,target_digest:target.digest,expected_revision:target.revision,reason:element("reason").value};const response=await fetch("/api/commands/prepare",{method:"POST",headers:{Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"},body:JSON.stringify(command)});const result=await response.json();if(!response.ok)throw new Error(result.detail||"명령 준비 실패");prepared=result;element("prepared").textContent=JSON.stringify(result,null,2);}));
element("command").addEventListener("submit",event=>{event.preventDefault();report(async()=>{if(!prepared)throw new Error("준비된 명령이 없습니다.");const authorization=element("command-token").value;element("command-token").value="";element("execute").disabled=true;const response=await fetch("/api/commands",{method:"POST",headers:{Authorization:`Bearer ${authorization}`,"Content-Type":"application/json"},body:JSON.stringify(prepared.command)});const result=await response.json();if(!response.ok)throw new Error(result.detail||"작업 실패");prepared=null;element("prepared").textContent="";await refresh();element("notice").textContent="처리 완료";});});window.addEventListener("resize",draw);